version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
    ports:
      - "6543:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"

  myjira:
    image: myjira-app
    build: ./
    container_name: myjira-container
    restart: always
    environment:
      CONFIG_PATH: ./config/
    ports:
      - "8080:8090"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
