CREATE TABLE roles(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) unique,
    description text
);

CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) not null unique,
    password_hash varchar(255) not null,
    full_name varchar(255) not null,
    email varchar not null unique,
    role_id int references roles(id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

CREATE TABLE ticket_types (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    description text
);

CREATE TABLE statuses (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    description text
);

CREATE TABLE stages (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE priorities (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE projects (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    resume varchar(255),
    description text,
    code varchar(255),
    project_lead_id int references users(id) on delete cascade not null,
    project_start_date timestamptz,
    project_end_date timestamptz
);

CREATE TABLE tickets (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id int references projects(id) on delete cascade not null,
    ticket_type_id int references ticket_types(id) on delete cascade not null,
    ticket_summary text,
    ticket_description text,
    reporter_id int references users(id) on delete cascade not null,
    assignee_id int references users(id) on delete cascade not null,
    status_id int references statuses(id) on delete cascade not null,
    stage_id int references stages(id) on delete cascade not null,
    priority_id int references priorities(id) on delete cascade not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    resolved_at timestamptz
);

CREATE TABLE comments (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id int references tickets(id) on delete cascade not null,
    user_id int references users(id) on delete cascade not null,
    comment_text text,
    created_at timestamptz not null
);

CREATE TABLE users_projects (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int references users(id) on delete cascade not null,
    project_id int references projects(id) on delete cascade not null
);

-- Indexes for 'users' table
CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_email ON users (email);

-- Indexes for 'projects' table
CREATE INDEX idx_projects_name ON projects (name);

-- Indexes for 'issues' table
CREATE INDEX idx_issues_project_id ON tickets (project_id);
CREATE INDEX idx_issues_reporter_id ON tickets (reporter_id);
CREATE INDEX idx_issues_assignee_id ON tickets (assignee_id);
CREATE INDEX idx_issues_status_id ON tickets (status_id);


-- Indexes for 'comments' table
CREATE INDEX idx_comments_issue_id ON comments (ticket_id);
CREATE INDEX idx_comments_user_id ON comments (user_id);

